
import React, { useEffect, useState } from 'react';
import { 
  ArrowLeft, ShieldCheck, Brain, Lock, Mic, Mail, Info, 
  Scale, Send, CheckCircle, AlertCircle, Sparkles, 
  Layers, Zap, Heart, Layout, Database, BookOpen
} from 'lucide-react';

interface PrivacyPolicyProps {
  onBack: () => void;
}

export const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onBack }) => {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setStatus('loading');

    const form = e.currentTarget;
    const data = new FormData(form);

    try {
      const response = await fetch('https://formspree.io/f/mqaeapzo', {
        method: 'POST',
        body: data,
        headers: {
          'Accept': 'application/json'
        }
      });

      if (response.ok) {
        setStatus('success');
        form.reset();
      } else {
        setStatus('error');
      }
    } catch (error) {
      setStatus('error');
    }
  };

  return (
    <div className="pt-32 pb-24 bg-white animate-fade-in-up">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <button 
          onClick={onBack}
          className="flex items-center space-x-2 text-indigo-600 hover:text-indigo-700 mb-12 font-medium transition-colors group"
        >
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
          <span>Back to Home</span>
        </button>

        <header className="mb-16">
          <div className="inline-flex items-center space-x-3 bg-indigo-50 text-indigo-600 px-4 py-2 rounded-xl mb-6">
            <Sparkles size={20} />
            <span className="font-bold tracking-tight uppercase text-xs">Framework & Transparency</span>
          </div>
          <h1 className="serif text-4xl md:text-6xl font-bold text-slate-900 leading-tight mb-4">
            Happier Decisions
          </h1>
          <p className="text-2xl italic text-slate-500 font-medium">
            "Decide with Logic. Act with Intuition."
          </p>
          <div className="mt-4 flex items-center space-x-2 text-slate-400">
            <BookOpen size={16} />
            <span className="text-sm">Based on the book 'Hopping for Happiness'</span>
          </div>
        </header>

        <div className="space-y-20">
          {/* How it Works Section */}
          <section className="space-y-10">
            <div className="flex items-center space-x-3">
              <Layers className="text-indigo-600" size={28} />
              <h2 className="serif text-3xl font-bold text-slate-900">How it Works (The Framework)</h2>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {[
                {
                  title: "Identify Your Values",
                  desc: "Choose from a list of core happiness factors or add your own unique drivers.",
                  icon: <Heart className="text-rose-500" />
                },
                {
                  title: "The Comparison Engine",
                  desc: "Compare factors head-to-head. Our algorithm creates a custom weight based on your current stage of life.",
                  icon: <Scale className="text-amber-500" />
                },
                {
                  title: "Evaluate Impact",
                  desc: "Score how your choice will affect each factor on a scale of -2 to 2.",
                  icon: <Zap className="text-indigo-500" />
                },
                {
                  title: "AI Analysis",
                  desc: "Receive a tailored breakdown of your decision generated by Claude or Gemini models.",
                  icon: <Brain className="text-purple-500" />
                }
              ].map((item, idx) => (
                <div key={idx} className="p-6 bg-slate-50 rounded-2xl border border-slate-100 flex flex-col h-full">
                  <div className="bg-white p-2.5 rounded-xl shadow-sm w-fit mb-4">
                    {item.icon}
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2">{item.title}</h3>
                  <p className="text-slate-600 text-sm leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>

            {/* Logic Score Highlight */}
            <div className="bg-slate-900 text-white p-8 rounded-3xl relative overflow-hidden">
               <div className="absolute top-0 right-0 p-8 opacity-10">
                 <Brain size={120} />
               </div>
               <div className="relative z-10">
                 <h3 className="serif text-2xl font-bold mb-4">The Logic Score</h3>
                 <p className="text-slate-300 mb-6 leading-relaxed max-w-xl">
                   We multiply the Priority level (determined by your comparisons) by the Expected Impact. 
                   This creates a weighted sum that reflects your true values in the context of your specific dilemma.
                 </p>
                 <div className="bg-white/10 backdrop-blur-md p-4 rounded-xl inline-block">
                    <p className="font-bold text-indigo-300 italic">
                      "Logic score + Intuition check = A decision you can live with."
                    </p>
                 </div>
               </div>
            </div>
          </section>

          {/* Why Choose Section */}
          <section className="space-y-8">
            <div className="flex items-center space-x-3">
              <ShieldCheck className="text-indigo-600" size={28} />
              <h2 className="serif text-3xl font-bold text-slate-900">Why Choose Happier Decisions?</h2>
            </div>
            
            <div className="grid grid-cols-1 gap-4">
              <div className="flex items-start space-x-4 p-6 bg-indigo-50 rounded-2xl">
                <div className="mt-1 bg-white p-2 rounded-lg text-indigo-600 shadow-sm"><Lock size={20} /></div>
                <div>
                  <h4 className="font-bold text-slate-900">Privacy First</h4>
                  <p className="text-slate-600 text-sm">Your dilemmas are personal. We don't have accounts or servers. Everything is stored locally on your device.</p>
                </div>
              </div>
              <div className="flex items-start space-x-4 p-6 bg-slate-50 rounded-2xl">
                <div className="mt-1 bg-white p-2 rounded-lg text-indigo-600 shadow-sm"><Zap size={20} /></div>
                <div>
                  <h4 className="font-bold text-slate-900">No Choice Paralysis</h4>
                  <p className="text-slate-600 text-sm">We break complex life choices into simple, bite-sized comparisons that make sense of the noise.</p>
                </div>
              </div>
              <div className="flex items-start space-x-4 p-6 bg-slate-50 rounded-2xl">
                <div className="mt-1 bg-white p-2 rounded-lg text-indigo-600 shadow-sm"><Brain size={20} /></div>
                <div>
                  <h4 className="font-bold text-slate-900">Intuition Integration</h4>
                  <p className="text-slate-600 text-sm">We don't just give you a number; we help you cross-reference the math with your "Gut Feeling."</p>
                </div>
              </div>
            </div>
          </section>

          {/* Pro Features Section */}
          <section className="space-y-8 p-8 bg-amber-50 rounded-[2.5rem] border border-amber-100">
            <div className="flex items-center space-x-3 mb-2">
              <div className="bg-amber-500 text-white p-1.5 rounded-full"><Sparkles size={16} /></div>
              <h2 className="serif text-3xl font-bold text-slate-900">Pro Features</h2>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-3">
                <div className="flex items-center space-x-2 text-amber-700 font-bold">
                  <Mic size={18} />
                  <span>Voice Dilemmas</span>
                </div>
                <p className="text-slate-600 text-sm">Speak your mind and let AI extract the factors for you automatically.</p>
              </div>
              <div className="space-y-3">
                <div className="flex items-center space-x-2 text-amber-700 font-bold">
                  <Layout size={18} />
                  <span>Custom Themes</span>
                </div>
                <p className="text-slate-600 text-sm">Personalize your results page with your own imagery and aesthetic.</p>
              </div>
              <div className="space-y-3">
                <div className="flex items-center space-x-2 text-amber-700 font-bold">
                  <Database size={18} />
                  <span>Expanded Factors</span>
                </div>
                <p className="text-slate-600 text-sm">Manage a library of up to 10 custom factors for deep, granular analysis.</p>
              </div>
            </div>
          </section>

          {/* Legal Sections */}
          <div className="pt-20 border-t border-slate-100 space-y-16">
            <section className="space-y-8">
              <div className="flex items-center space-x-3">
                <Lock className="text-slate-400" size={24} />
                <h2 className="serif text-3xl font-bold text-slate-900">Privacy Policy</h2>
              </div>
              
              <div className="grid grid-cols-1 gap-8">
                <div className="flex gap-4">
                  <div className="mt-1 bg-slate-100 p-2 rounded-lg h-fit text-slate-600"><Info size={18} /></div>
                  <div>
                    <h3 className="font-bold text-slate-900 mb-2">Data Ownership</h3>
                    <p className="text-slate-600 leading-relaxed text-sm">
                      Your data is yours. We use local storage on your device and never store your decisions on our servers.
                    </p>
                  </div>
                </div>

                <div className="flex gap-4">
                  <div className="mt-1 bg-slate-100 p-2 rounded-lg h-fit text-slate-600"><Brain size={18} /></div>
                  <div>
                    <h3 className="font-bold text-slate-900 mb-2">AI Processing</h3>
                    <p className="text-slate-600 leading-relaxed text-sm">
                      This app uses the Google Gemini or Claude API to analyze your decision dilemmas. By using the AI feature, you consent to your dilemma text (and audio for Pro users) being sent to Google or Claude for processing. We do not store these recordings on our own infrastructure.
                    </p>
                  </div>
                </div>

                <div className="flex gap-4">
                  <div className="mt-1 bg-slate-100 p-2 rounded-lg h-fit text-slate-600"><Mic size={18} /></div>
                  <div>
                    <h3 className="font-bold text-slate-900 mb-2">Permissions</h3>
                    <p className="text-slate-600 leading-relaxed text-sm">
                      Microphone access is only requested for the Voice Dilemma feature and is never active when the app is in the background.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            <section className="space-y-6 pt-12 border-t border-slate-100">
              <div className="flex items-center space-x-3">
                <Scale className="text-slate-400" size={24} />
                <h2 className="serif text-3xl font-bold text-slate-900">Terms of Use</h2>
              </div>
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 space-y-4">
                <p className="text-slate-700 leading-relaxed text-sm">
                  This application is a tool to assist with personal decision-making. The "Happier Decisions" team and authors of "Hopping for Happiness" are not responsible for any outcomes resulting from decisions made using this framework. Use your best judgment.
                </p>
                <p className="text-slate-700 leading-relaxed text-sm">
                  By using this app, you also agree to the <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline font-medium">Apple Standard EULA</a>.
                </p>
                <div className="pt-4 border-t border-slate-200">
                  <h4 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2 flex items-center">
                    <Sparkles size={14} className="mr-1" />
                    A Note on AI
                  </h4>
                  <p className="text-slate-600 leading-relaxed text-sm italic">
                    We use state-of-the-art AI technology to support you in the best possible way. However, since AI can sometimes "hallucinate" (make small mistakes), we have tested the app extensively and are constantly optimizing it. Your feedback helps us make the app better every day!
                  </p>
                </div>
              </div>
            </section>
          </div>

          {/* Contact Form Section */}
          <section id="contact" className="pt-20 border-t border-slate-100">
            <div className="text-center mb-8">
              <div className="inline-flex items-center justify-center bg-indigo-600 text-white p-3 rounded-full mb-4">
                <Mail size={24} />
              </div>
              <h2 className="serif text-2xl font-bold text-slate-900">Contact Us</h2>
              <p className="text-slate-500 max-w-md mx-auto">
                If you have questions about the Happier Decisions framework or our policies, please reach out.
              </p>
            </div>

            <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100 shadow-sm">
              {status === 'success' ? (
                <div className="py-12 flex flex-col items-center justify-center text-center space-y-4 animate-fade-in-up">
                  <div className="bg-green-100 p-4 rounded-full text-green-600">
                    <CheckCircle size={48} />
                  </div>
                  <h3 className="serif text-2xl font-bold text-slate-900">Message Sent!</h3>
                  <p className="text-slate-600">Thank you for reaching out. Your message has been received and we'll get back to you soon.</p>
                  <button 
                    onClick={() => setStatus('idle')}
                    className="text-indigo-600 font-semibold hover:underline"
                  >
                    Send another message
                  </button>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <input 
                      type="text" 
                      name="name" 
                      required 
                      placeholder="Name"
                      className="w-full bg-white border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                    />
                    <input 
                      type="email" 
                      name="email" 
                      required 
                      placeholder="Email"
                      className="w-full bg-white border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                    />
                  </div>
                  <textarea 
                    name="message" 
                    required 
                    rows={4}
                    placeholder="Your inquiry..."
                    className="w-full bg-white border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:ring-2 focus:ring-indigo-500 outline-none transition-all resize-none"
                  ></textarea>
                  
                  {status === 'error' && (
                    <div className="flex items-center space-x-2 text-red-600 bg-red-50 p-3 rounded-lg text-sm">
                      <AlertCircle size={18} />
                      <span>Something went wrong. Please try again later.</span>
                    </div>
                  )}

                  <button 
                    type="submit" 
                    disabled={status === 'loading'}
                    className="w-full flex items-center justify-center space-x-2 bg-indigo-600 text-white px-8 py-3.5 rounded-xl font-bold hover:bg-indigo-700 transition-all shadow-md disabled:opacity-50"
                  >
                    {status === 'loading' ? (
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                    ) : (
                      <>
                        <span>Send Message</span>
                        <Send size={18} />
                      </>
                    )}
                  </button>
                  <p className="text-center text-xs text-slate-400 mt-4">
                    Direct inquiries: booksandappsbyeja@gmail.com
                  </p>
                </form>
              )}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};
